### ISSUE TITLE
plots

### ISSUE THREAD

**Issue by jwijffels** [adjidieng/ETM-R#3]
Hello @adjidieng and @p-lin 
Thank you for the implementation of ETM. I've been reading the paper and the Python code in order to build an R version that directly uses the torch package and the word2vec package instead of this ETM-R reticulate interface.

I like the plot on the Figures 2 and 3 from the paper https://arxiv.org/pdf/1907.04907.pdf and wonder how you have mapped the topic and word vectors to 2 dimensions to plot them? Any hints about that? Was it UMAP?

**Comment by jwijffels** [comment]
@adjidieng / @p-lin I've put the R package at https://github.com/bnosac/ETM
It's a rewrite of the Python code at https://github.com/adjidieng/ETM using the R package torch which is an interface on the libtorch C++ library. 
Would be great if you could indicate how you made these plots so that I can add this functionality in the package.

**Comment by p-lin** [comment]
Hello!  Awesome job with your R package!  Seems like we have different approaches, for example how you use the word2vec library in R to fit word embeddings, whereas I use the gensim library in python.  I guess R users will have more choices with regards to using ETM, which is always good.  

With regards to the plots, I agree with you, and Adji will be much better at answering that question.  I will raise the issue next time I chat with her.

**Comment by adjidieng** [comment]
Hello @jwijffels,

Thank you for implementing ETM in R. I just checked and there’s a confusion regarding the Licensing and Copyright. 

ETM is under the MIT License with copyright as indicated in the file attached. I see you added yourself as copyright holder, see the other image attached. Please correct this.

Thank you,
Adji.



>

**Comment by jwijffels** [comment]
Hello @adjidieng / @p-lin 

- I can certainly make modifications on the license / copyright information if you like that. Probably you haven't seen https://github.com/bnosac/ETM/blob/master/LICENSE.note yet. I've created an issue at https://github.com/bnosac/ETM/issues/1, feel free to let me know how I need to make changes to your wishes on there
- I'm planning to add the The Dynamic Embedded Topic Model https://github.com/adjidieng/DETM in a similar way using the same Python-agnostic setup on top of libtorch using https://torch.mlverse.org. If you have remarks about that, let me know.
- My apologies for tagging both of you with that @ symbol and hence spamming your email box (I just wasn't sure if you are frequently using github and wouldn't see these messages). If you think this is inappropriate, let me know

If you have information on how you created Figures 2 and 3 from the paper https://arxiv.org/pdf/1907.04907.pdf, that would be great.

**Comment by jwijffels** [comment]
Closing as there is no feedback from the authors regarding these questions / remarks.
